using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.Build.Framework;

namespace SqlUserTypeGenerator
{
    public class SqlGeneratorTask : ITask
    {
	    private static string StaticSourceAssemblyPath;

		public bool Execute()
		{

			StaticSourceAssemblyPath = SourceAssemblyPath;
			
			var destFolderAbsolutePath = Path.GetFullPath(DestinationFolder);

            //BuildEngine.LogMessageEvent(new BuildMessageEventArgs("test custom task", destFolderAbsolutePath, "sender", MessageImportance.High));

            if (!Directory.Exists(destFolderAbsolutePath))
            {
                Directory.CreateDirectory(destFolderAbsolutePath);
            }			

			var headerText = GetHeaderText();

			var generatedSql = string.Empty;
			AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve += CurrentDomain_ReflectionOnlyAssemblyResolve;
			var assembly = Assembly.ReflectionOnlyLoadFrom(SourceAssemblyPath);

			var types = assembly.GetTypes().Where(t => t.GetCustomAttributesData().Any()).ToList();			

			foreach (var type in types)
			{
				Console.WriteLine(type.FullName);
				var generatedType = SqlGenerator.GenerateUserType(type);				

				generatedSql =
					$"if object_id('{generatedType.TypeName}') is not null drop type [{generatedType.TypeName}];\r\ngo\r\n\r\n"
					+ $"create type [{generatedType.TypeName}] as table ( \r\n"
					+ string.Join(",\r\n", generatedType.Columns.Select(c => "\t" + c))
					+ "\r\n)\r\ngo";

				var targetFile = Path.ChangeExtension(Path.Combine(destFolderAbsolutePath, GetSafeFilename(generatedType.TypeName)), "sql");

				File.WriteAllText(targetFile, headerText + generatedSql, Encoding.UTF8);
			}

			return true;
        }

	    private static Assembly CurrentDomain_ReflectionOnlyAssemblyResolve(object sender, ResolveEventArgs args)
	    {		    

		    var sqlUserTypeGeneratorAssemblyPath = Path.Combine(Path.GetDirectoryName(StaticSourceAssemblyPath),
			    "SqlUserTypeGenerator.dll");

			var currentDomainReflectionOnlyAssemblyResolve = Assembly.ReflectionOnlyLoadFrom(sqlUserTypeGeneratorAssemblyPath);

			Console.WriteLine($"out {nameof(CurrentDomain_ReflectionOnlyAssemblyResolve)}, codebase: {currentDomainReflectionOnlyAssemblyResolve.CodeBase}");

			return currentDomainReflectionOnlyAssemblyResolve;
	    }


		private string GetHeaderText()
        {
            var assembly = typeof(SqlGeneratorTask).Assembly;
            var an = assembly.GetName().Name;
            var av = assembly.GetName().Version.ToString();
            return $"--autogenerated by {an} v{av}\r\n\r\n";
        }

        private string GetSafeFilename(string filename)
        {

            return string.Join("", filename.Split(Path.GetInvalidFileNameChars()));

        }

        public string SourceAssemblyPath { get; set; }
        public string DestinationFolder { get; set; }

        public IBuildEngine BuildEngine { get; set; }
        public ITaskHost HostObject { get; set; }
    }
}
