using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.Build.Framework;

namespace SqlUserTypeGenerator
{
    public class SqlGeneratorTask : ITask
    {
		public bool Execute()
		{
						
			var destFolderAbsolutePath = Path.GetFullPath(DestinationFolder);

            //BuildEngine.LogMessageEvent(new BuildMessageEventArgs("test custom task", destFolderAbsolutePath, "sender", MessageImportance.High));

            if (!Directory.Exists(destFolderAbsolutePath))
            {
                Directory.CreateDirectory(destFolderAbsolutePath);
            }						
			
			AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve += CurrentDomain_ReflectionOnlyAssemblyResolve;

			LoadDependentAssemblies(SourceAssemblyPath);

			//load target assembly
			Assembly assembly = Assembly.ReflectionOnlyLoadFrom(SourceAssemblyPath); ;

			//get classes with custom attribute			
			var types = assembly.GetTypes()
				.Select(t =>
					new UserTypeWithSqlUserTypeAttribute()
					{
						UserType = t,
						SqlUserTypeAttributeData = CustomAttributesHelper.GetSqlUserTypeAttributeData(t)
					})
				.Where(ut => ut.SqlUserTypeAttributeData != null)
				.ToList()
				;

			var headerText = GetHeaderText();
			foreach (var type in types)
			{				
				var generatedType = SqlGenerator.GenerateUserType(type.UserType, type.SqlUserTypeAttributeData);
				
				var generatedSql =
					$"if type_id('{generatedType.TypeName}') is not null drop type [{generatedType.TypeName}];\r\ngo\r\n\r\n"
					+ $"create type [{generatedType.TypeName}] as table ( \r\n"
					+ string.Join(",\r\n", generatedType.Columns.Select(c => "\t" + c))
					+ "\r\n)\r\ngo";

				var targetFile = Path.ChangeExtension(Path.Combine(destFolderAbsolutePath, GetSafeFilename(generatedType.TypeName)), "sql");

				File.WriteAllText(targetFile, headerText + generatedSql, Encoding.UTF8);
			}

			return true;
        }

	    private void LoadDependentAssemblies(string sourceAssemblyPath)
	    {
			//load all assemblies in project output folder to reflection-only context
		    var directoryName = Path.GetDirectoryName(sourceAssemblyPath);

		    var files = Directory.GetFiles(directoryName)
			    .Where(f => StringHelper.IsEqualStrings(Path.GetExtension(f), ".dll"));

		    foreach (var file in files)
		    {
			    Assembly.ReflectionOnlyLoadFrom(file);
		    }
	    }

	    internal class UserTypeWithSqlUserTypeAttribute
	    {
		    public Type UserType { get; set; }
		    public CustomAttributeData SqlUserTypeAttributeData { get; set; }
	    }


	    private Assembly CurrentDomain_ReflectionOnlyAssemblyResolve(object sender, ResolveEventArgs args)
	    {
		    string missedAssemblyFullName = args.Name;
		    Assembly assembly = Assembly.ReflectionOnlyLoad(missedAssemblyFullName);
		    return assembly;
	    }

		private string GetHeaderText()
        {
            var assembly = typeof(SqlGeneratorTask).Assembly;
            var an = assembly.GetName().Name;
            var av = assembly.GetName().Version.ToString();
            return $"--autogenerated by {an} v{av}\r\n\r\n";
        }

        private string GetSafeFilename(string filename)
        {

            return string.Join("", filename.Split(Path.GetInvalidFileNameChars()));

        }

        public string SourceAssemblyPath { get; set; }
        public string DestinationFolder { get; set; }

        public IBuildEngine BuildEngine { get; set; }
        public ITaskHost HostObject { get; set; }
    }
}
