--autogenerated by SqlUserTypeGenerator v1.0.0.0

create type [t_DbClasses_user] as table (
	PropLong bigint not null,
	PropLongNull bigint null,
	PropString nvarchar(10) not null,
	PropBool bit not null,
	PropBoolNull bit null,
	PropDateTime datetime not null,
	PropDateTimeNull datetime null,
	PropDecimal numeric(7, 3) not null,
	PropDecimalNull numeric(10, 2) null,
	DefaultPrecisionNumeric numeric(18) not null,
	PropDouble float not null,
	PropDoubleNull float null,
	PropInt int not null,
	PropIntNull int null,
	PropGuid uniqueidentifier not null,
	PropGuidNull uniqueidentifier null,
	NullableString nvarchar(50) null,
	PropByteArray varbinary(50) not null,
	PropByte tinyint not null,
	PropByteNull22 tinyint null,
	BaseProp nvarchar(23) not null
)
go