--autogenerated by SqlUserTypeGenerator v1.0.0.0


if type_id(N'[t_DbClassesWithCustomSqlFolder_user]') is not null drop type [t_DbClassesWithCustomSqlFolder_user]
go

create type [t_DbClassesWithCustomSqlFolder_user] as table ( 
	PropLong bigint not null,
	PropLongNull bigint null,
	PropString nvarchar(42) not null,
	PropBool bit not null,
	PropBoolNull bit null,
	PropDateTime datetime not null,
	PropDateTime2 datetime not null,
	PropDateTimeNull datetime null,
	ExplicitPropDateTime datetime not null,
	ExplicitPropDateTime2 datetime2 not null,
	ExplicitPropDate date not null,
	PropDecimal numeric(18) not null,
	PropDecimalNull numeric(18) null,
	PropDouble float not null,
	PropDoubleNull float null,
	PropInt int not null,
	PropIntNull int null,
	PropGuid uniqueidentifier not null,
	PropGuidNull uniqueidentifier null,
	PropByteArray varbinary not null,
	PropByte tinyint not null,
	PropByteNull tinyint null
)
go

print 't_DbClassesWithCustomSqlFolder_user type re-created'
