# This is a basic workflow to help you get started with Actions

name: Publish SqlUserTypeGenerator Package to Nuget

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v3
     
     - name: Setup NuGet
       uses: NuGet/setup-nuget@v1.0.6
       
     - name: Setup Msbuild
       uses: microsoft/setup-msbuild@v1.1
     - name: Restore dependencies
       run: nuget restore SqlUserTypeGenerator.sln
       
     - name: Create package
       run: | 
         msbuild .\SqlUserTypeGenerator\SqlUserTypeGenerator.csproj /p:Configuration=Release
         nuget pack .\SqlUserTypeGenerator\SqlUserTypeGenerator.nuspec
         
     - name: Publish package
       run: nuget push  **\*.nupkg -apikey ${{secrets.NUGET_API_KEY}} -Source https://www.nuget.org/api/v2/package
       

